server:
  port: 8081
  servlet:
    context-path: /ticket

spring:
  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
  #数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/world?characterEncoding=UTF8&serverTimezone=UTC&useUnicode=true&allowMultiQueries=true
    username: root
    password: dreamsoft
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 1
      min-idle: 1
      max-idle: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  #rabbitMQ
  application:
    name: spirng-boot-rabbitmq-sender
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest